name: Release
on:
  workflow_dispatch:
    inputs:
      version:
        type: string
        description: Runtipi version to use (v3.6.0, nightly...)
        required: true
      distinct_id:
        type: string
        description: Distinct ID for the release
        required: true

jobs:
  create-tag:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Create tag
        uses: rickstaa/action-create-tag@v1
        with:
          tag: ${{ github.event.inputs.version }}

  build:
    needs: create-tag
    runs-on: ubuntu-latest
    steps:
      - name: Distinct ID
        run: echo ${{ github.event.inputs.distinct_id }}

      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: "1.22.5"

      - name: Set version
        run: echo ${{ github.event.inputs.version }} > internal/constants/assets/VERSION

      - name: Build CLI for amd64
        run: GOOS=linux GOARCH=arm64 go build -ldflags '-w -s' . && mv runtipi-cli-go runtipi-cli-go-arm64

      - name: Build CLI for arm64
        run: GOOS=linux GOARCH=amd64 go build -ldflags '-w -s' . && mv runtipi-cli-go runtipi-cli-go-amd64

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: binaries
          path: |
            runtipi-cli-go-arm64
            runtipi-cli-go-amd64

  release:
    needs: [create-tag, build]
    runs-on: ubuntu-latest
    steps:
      - name: Download artifacts
        uses: actions/download-artifact@v4
        with:
          name: binaries
          path: binaries

      - name: Create release
        uses: softprops/action-gh-release@v2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          prerelease: false
          tag_name: ${{ github.event.inputs.version }}
          name: ${{ github.event.inputs.version }}
          files: binaries/*
